### ISSUE TITLE
Deploy automation

### ISSUE THREAD

**Issue by Eomm** [fastify/pacchetto#1]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

Create a GitHub action that triggers the deployment:

```
npm run generate
rm -rf docs && cp -r dist/client docs
# and push everything to main
```

**Comment by simoneb** [comment]
Folks I would do this differently. There are already github actions capable of publishing stuff to github pages. Just pick one of those and configure the repo accordingly. Usually (and I prefer that too) they use a different branch but I'm sure they can be configured differently if you want to keep stuff in docs.

**Comment by simoneb** [comment]
@davideroffo can you take a look at this?

**Comment by davideroffo** [comment]
@simoneb I created a PR for solving this issue here: https://github.com/fastify/pacchetto/pull/4
