### ISSUE TITLE
update to @fastify/module-name

### ISSUE THREAD

**Issue by Eomm** [fastify/pacchetto#6]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Plugin version

-

### Node.js version

-

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

We should update pacchetto to see the new `@fastify/module` names:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/11404065/179365344-c36892b0-18e2-4d41-b0b4-7165d39a18d7.png">

### Steps to Reproduce

-

**Comment by nasainsbury** [comment]
I've attempted to address this issue in this PR: https://github.com/fastify/pacchetto/pull/7
